### ISSUE TITLE
Bump version to 0.5.1 ?

### ISSUE THREAD

**Issue by jechol** [wokalski/Diff.swift#35] opened 2017-01-12 09:41 UTC
Thanks for merge.

Could you release 0.5.1 with latest commit?

I know that there is no change in source,
but last digit would fit with .ignore change.

My purpose is to change ReactiveKit/Bond podspec to depend on 0.5.1
so that no more git dirty state after just running `carthage update` in Bond.
(I'm not a author of Bond, just wanna make contributors like me feel better)

Thanks for great library!

**Comment by wokalski** [comment] 2017-01-12 09:59
You can do it now! 👍 but sure, I can do it, too later in the day.

**Comment by jechol** [comment] 2017-01-12 10:18
I don't have any prior experience related with Github release process, so this is my first try.

I created a release in my fork at https://github.com/jechol/Diff.swift/releases,
what should I do from here?

It would be great if I can release this myself.

**Comment by wokalski** [comment] 2017-01-12 10:23
1. please wait for [this](https://travis-ci.org/wokalski/Diff.swift/jobs/191206827) and associated PR to be merged.
2. Update version in the `podspec` to point to `0.5.1` and create a PR (please include `[ci skip]` in the commit message to avoid rebuilding it on travis (like `[ci skip] version 0.5.1`).
3. Create a release on github just like you made in your repository, but here.

Afterwards I'll push the pod spec.

**Comment by wokalski** [comment] 2017-01-12 10:24
Oh, and please accept my invite for you to be a `Collaborator`.

**Comment by wokalski** [comment] 2017-01-12 10:50
fixed in #36

**Closed** 2017-01-12 10:49 UTC

**Comment by tonyarnold** [comment] 2017-01-12 11:43
> My purpose is to change ReactiveKit/Bond podspec to depend on 0.5.1

I'll take care of that - just battling Travis CI at the moment. When it's passing, I'll get it into master.

**Comment by wokalski** [comment] 2017-01-12 11:57
If you mean battling Travis here, then I'd let go. Non deterministic, failing builds are annoying but the issue is apparently within travis/simulator. This repo is relatively calm so restarting one or two jobs a week doesn't bother me this much.

Of course any contribution is welcome but I'm worried that it's just a waste of time.

**Comment by tonyarnold** [comment] 2017-01-12 11:58
No, no, I'm battling it over on Bond's repo right now. Error 65 😑 

I'm using their `travis_retry` workaround - I'll let you know how it goes.

**Comment by wokalski** [comment] 2017-01-12 12:03
[This](https://github.com/travis-ci/travis-ci/issues/6675#issuecomment-257964767) also seems promisisng

**Comment by jechol** [comment] 2017-01-12 13:49
@tonyarnold I would appreciate if you would handle the upgrading to 0.5.1. Thanks.

**Comment by tonyarnold** [comment] 2017-01-12 21:32
Bond has been updated to include v0.5.1: https://github.com/ReactiveKit/Bond/pull/357

**Comment by jechol** [comment] 2017-01-13 00:49
Great!
